[package]
name = "diesel-factories"
version = "0.0.1"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.3" }
diesel-factories-code-gen = { version = "0.0.1", path = "../diesel-factories-code-gen" }

[dev_dependencies]
diesel = { version = "1.3.3", features = ["postgres"] }
